import type { PayrollRun, PayrollPayslip } from '../types';

let jsPDF: any = null;

async function getJsPDF() {
  if (!jsPDF) {
    const mod = await import('jspdf');
    jsPDF = mod.jsPDF;
  }
  return jsPDF;
}

function formatNGN(amount: number): string {
  return `₦${amount.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;
}

function addHeader(doc: any, title: string, subtitle?: string) {
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('AURA', 15, 20);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128);
  doc.text('Finance AI', 15, 26);
  doc.setTextColor(0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 15, 40);
  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 15, 47);
  }
  doc.setDrawColor(200);
  doc.line(15, 50, 195, 50);
  return 55;
}

function addFooter(doc: any) {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Generated by Aura Finance AI', 15, 285);
  doc.text(`Printed: ${new Date().toLocaleDateString()}`, 15, 290);
}

export async function generatePayslipPDF(payslip: PayrollPayslip, period: string, companyName: string = 'Aura Corp'): Promise<void> {
  const PDF = await getJsPDF();
  const doc = new PDF();

  let y = addHeader(doc, 'SALARY PAYSLIP', `Period: ${period}`);

  // Company info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(companyName, 15, y);
  doc.setFont('helvetica', 'normal');
  doc.text(`Pay Period: ${period}`, 120, y);
  y += 10;

  // Employee info
  doc.setFillColor(245, 245, 245);
  doc.rect(15, y, 180, 20, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Employee Name:', 20, y + 7);
  doc.text('Employee ID:', 20, y + 14);
  doc.setFont('helvetica', 'normal');
  doc.text(payslip.employeeName, 60, y + 7);
  doc.text(payslip.employeeId.slice(-8).toUpperCase(), 60, y + 14);
  y += 25;

  // Earnings
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('EARNINGS', 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const earnings: [string, number][] = [
    ['Basic Salary', payslip.grossSalary],
    ['Bonus', payslip.bonus],
  ];
  for (const [label, amount] of earnings) {
    doc.text(label, 20, y);
    doc.text(formatNGN(amount), 120, y);
    doc.line(15, y + 3, 195, y + 3);
    y += 7;
  }
  doc.setFont('helvetica', 'bold');
  doc.text('Total Earnings', 20, y);
  doc.text(formatNGN(payslip.totalIncome), 120, y);
  y += 12;

  // Deductions
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('DEDUCTIONS', 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const deductions: [string, number][] = [
    ['PAYE Tax', payslip.paye],
    ['Pension (10%)', payslip.pension],
    ['NHF (2.5%)', payslip.nhf],
    ['Other Deductions', payslip.deduction],
  ];
  for (const [label, amount] of deductions) {
    doc.text(label, 20, y);
    doc.text(formatNGN(amount), 120, y);
    doc.line(15, y + 3, 195, y + 3);
    y += 7;
  }
  doc.setFont('helvetica', 'bold');
  doc.text('Total Deductions', 20, y);
  doc.text(formatNGN(payslip.totalDeductions), 120, y);
  y += 12;

  // Net Pay
  doc.setFillColor(245, 245, 245);
  doc.rect(15, y - 3, 180, 14, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('NET PAY', 20, y + 5);
  doc.text(formatNGN(payslip.netSalary), 120, y + 5);

  addFooter(doc);
  doc.save(`Payslip-${payslip.employeeName.replace(/\s+/g, '-')}-${period.replace(/\s+/g, '-')}.pdf`);
}

export async function generatePayrollSummaryPDF(run: PayrollRun): Promise<void> {
  const PDF = await getJsPDF();
  const doc = new PDF();

  let y = addHeader(doc, 'PAYROLL SUMMARY', `Period: ${run.period}`);

  const s = run.summary;
  doc.setFontSize(10);
  const rows: [string, string][] = [
    ['Employees', String(s.employeeCount)],
    ['Total Gross', formatNGN(s.totalGross)],
    ['Total Bonuses', formatNGN(s.totalBonuses)],
    ['Total Deductions', formatNGN(s.totalDeductions)],
    ['Total PAYE', formatNGN(s.totalPAYE)],
    ['Total Pension', formatNGN(s.totalPension)],
  ];
  for (const [label, value] of rows) {
    doc.text(label, 15, y); doc.text(value, 120, y); y += 7;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Total Net Pay:', 15, y); doc.text(formatNGN(s.totalNet), 120, y); y += 14;

  // Payslips table
  doc.setFontSize(9);
  doc.setFillColor(245, 245, 245);
  doc.rect(15, y, 180, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Employee', 17, y + 5.5);
  doc.text('Gross', 80, y + 5.5);
  doc.text('Deductions', 115, y + 5.5);
  doc.text('Net', 160, y + 5.5);
  y += 10;

  doc.setFont('helvetica', 'normal');
  for (const p of run.payslips || []) {
    doc.text(p.employeeName, 17, y + 4);
    doc.text(formatNGN(p.grossSalary), 80, y + 4);
    doc.text(formatNGN(p.totalDeductions), 115, y + 4);
    doc.text(formatNGN(p.netSalary), 160, y + 4);
    y += 7;
  }

  addFooter(doc);
  doc.save(`Payroll-${run.period.replace(/\s+/g, '-')}.pdf`);
}

export async function generateAllPayslipsPDF(run: PayrollRun): Promise<void> {
  for (const payslip of run.payslips || []) {
    await generatePayslipPDF(payslip, run.period);
  }
}
