let jsPDF: any = null;

async function getJsPDF() {
  if (!jsPDF) {
    const mod = await import('jspdf');
    jsPDF = mod.jsPDF;
  }
  return jsPDF;
}

function formatNGN(amount: number): string {
  return `₦${amount.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;
}

function addHeader(doc: any, title: string, subtitle?: string) {
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('AURA', 15, 20);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128);
  doc.text('Finance AI', 15, 26);
  doc.setTextColor(0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 15, 40);
  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 15, 47);
  }
  doc.setDrawColor(200);
  doc.line(15, 50, 195, 50);
  return 55;
}

function addFooter(doc: any) {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Generated by Aura Finance AI', 15, 285);
}

export async function generateInvoicePDF(invoice: any): Promise<void> {
  const PDF = await getJsPDF();
  const doc = new PDF();
  let y = addHeader(doc, `INVOICE #${invoice.id.slice(-6).toUpperCase()}`, `Date: ${new Date(invoice.issueDate).toLocaleDateString()}`);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 15, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.customer, 15, y + 6);
  doc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, 120, y);
  doc.text(`Status: ${invoice.status}`, 120, y + 6);
  y += 16;

  doc.setFillColor(245, 245, 245);
  doc.rect(15, y, 180, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Description', 17, y + 5.5);
  doc.text('Qty', 110, y + 5.5);
  doc.text('Price', 130, y + 5.5);
  doc.text('Total', 160, y + 5.5);
  y += 10;

  doc.setFont('helvetica', 'normal');
  for (const item of invoice.lineItems || []) {
    doc.text(item.name || '', 17, y + 4);
    doc.text(String(item.quantity), 112, y + 4);
    doc.text(formatNGN(item.unitPrice || 0), 130, y + 4);
    doc.text(formatNGN(item.total), 160, y + 4);
    y += 7;
  }

  y += 3;
  doc.line(110, y, 195, y);
  y += 6;

  doc.text('Subtotal:', 130, y); doc.text(formatNGN(invoice.amount), 160, y); y += 6;
  doc.text('VAT (7.5%):', 130, y); doc.text(formatNGN(invoice.vat), 160, y); y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', 130, y); doc.text(formatNGN(invoice.total), 160, y);

  addFooter(doc);
  doc.save(`Invoice-${invoice.id.slice(-6).toUpperCase()}.pdf`);
}

export async function generateBillPDF(bill: any): Promise<void> {
  const PDF = await getJsPDF();
  const doc = new PDF();
  let y = addHeader(doc, `BILL #${bill.id.slice(-6).toUpperCase()}`, `From: ${bill.vendor}`);

  doc.setFontSize(10);
  doc.text(`Amount: ${formatNGN(bill.amount)}`, 15, y); y += 6;
  doc.text(`Due: ${new Date(bill.dueDate).toLocaleDateString()}`, 15, y); y += 6;
  doc.text(`Status: ${bill.status}`, 15, y); y += 10;

  if (bill.description) {
    doc.setFont('helvetica', 'bold');
    doc.text('Description:', 15, y); y += 6;
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(bill.description, 170);
    doc.text(lines, 15, y);
  }

  addFooter(doc);
  doc.save(`Bill-${bill.id.slice(-6).toUpperCase()}.pdf`);
}

export async function generatePayslipPDF(payslip: any, period: string): Promise<void> {
  const PDF = await getJsPDF();
  const doc = new PDF();
  let y = addHeader(doc, 'PAYSLIP', `Period: ${period}`);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Employee:', 15, y);
  doc.setFont('helvetica', 'normal');
  doc.text(payslip.employeeName, 50, y); y += 8;

  const rows: [string, string][] = [
    ['Gross Salary', formatNGN(payslip.grossSalary)],
    ['Bonus', formatNGN(payslip.bonus)],
    ['Deduction', formatNGN(payslip.deduction)],
    ['Total Income', formatNGN(payslip.totalIncome)],
    ['', ''],
    ['PAYE Tax', formatNGN(payslip.paye)],
    ['Pension (10%)', formatNGN(payslip.pension)],
    ['NHF (2.5%)', formatNGN(payslip.nhf)],
    ['Total Deductions', formatNGN(payslip.totalDeductions)],
    ['', ''],
  ];

  doc.setFont('helvetica', 'normal');
  for (const [label, value] of rows) {
    if (!label) { y += 3; continue; }
    doc.text(label, 15, y); doc.text(value, 120, y); y += 6;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Net Salary:', 15, y); doc.text(formatNGN(payslip.netSalary), 120, y);

  addFooter(doc);
  doc.save(`Payslip-${payslip.employeeName.replace(/\s+/g, '-')}-${period.replace(/\s+/g, '-')}.pdf`);
}

export async function generatePayrollSummaryPDF(run: any): Promise<void> {
  const PDF = await getJsPDF();
  const doc = new PDF();
  let y = addHeader(doc, 'PAYROLL SUMMARY', `Period: ${run.period}`);

  doc.setFontSize(10);
  const s = run.summary;
  const rows: [string, string][] = [
    ['Employees', String(s.employeeCount)],
    ['Total Gross', formatNGN(s.totalGross)],
    ['Total Bonuses', formatNGN(s.totalBonuses)],
    ['Total Deductions', formatNGN(s.totalDeductions)],
    ['Total PAYE', formatNGN(s.totalPAYE)],
    ['Total Pension', formatNGN(s.totalPension)],
  ];
  for (const [label, value] of rows) {
    doc.text(label, 15, y); doc.text(value, 120, y); y += 7;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Total Net Pay:', 15, y); doc.text(formatNGN(s.totalNet), 120, y); y += 14;

  doc.setFontSize(9);
  doc.setFillColor(245, 245, 245);
  doc.rect(15, y, 180, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Employee', 17, y + 5.5);
  doc.text('Gross', 80, y + 5.5);
  doc.text('Deductions', 115, y + 5.5);
  doc.text('Net', 160, y + 5.5);
  y += 10;

  doc.setFont('helvetica', 'normal');
  for (const p of run.payslips || []) {
    doc.text(p.employeeName, 17, y + 4);
    doc.text(formatNGN(p.grossSalary), 80, y + 4);
    doc.text(formatNGN(p.totalDeductions), 115, y + 4);
    doc.text(formatNGN(p.netSalary), 160, y + 4);
    y += 7;
  }

  addFooter(doc);
  doc.save(`Payroll-${run.period.replace(/\s+/g, '-')}.pdf`);
}