import type { Invoice, Bill } from '../types';

function formatNGN(amount: number): string {
  return `₦${amount.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;
}

export function shareInvoiceViaWhatsApp(invoice: Invoice) {
  const msg = [
    `📄 Invoice #${invoice.id.slice(-6).toUpperCase()}`,
    ``,
    `Client: ${invoice.customer}`,
    `Amount: ${formatNGN(invoice.total)}`,
    `Status: ${invoice.status}`,
    `Due: ${new Date(invoice.dueDate).toLocaleDateString()}`,
    ``,
    `Generated by Aura Finance AI`,
  ].join('\n');

  const url = `https://wa.me/?text=${encodeURIComponent(msg)}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

export function shareBillViaWhatsApp(bill: Bill) {
  const msg = [
    `📄 Bill #${bill.id.slice(-6).toUpperCase()}`,
    ``,
    `Vendor: ${bill.vendor}`,
    `Amount: ${formatNGN(bill.amount)}`,
    `Status: ${bill.status}`,
    `Due: ${new Date(bill.dueDate).toLocaleDateString()}`,
    ``,
    `Generated by Aura Finance AI`,
  ].join('\n');

  const url = `https://wa.me/?text=${encodeURIComponent(msg)}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

export function shareTextViaWhatsApp(text: string) {
  const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

export async function shareViaNative(title: string, text: string) {
  if (navigator.share) {
    try {
      await navigator.share({ title, text });
    } catch {
      // User cancelled
    }
  } else {
    shareTextViaWhatsApp(text);
  }
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  }
}
